require 'data'
require 'rake/rdoctask'

include TTime

class File
  class << self
    def try_unlink(*files)
      files.each do |file_name|
        begin
          File.unlink file_name
        rescue Errno::ENOENT
        end
      end
    end
  end
end

Rake::RDocTask.new("doc") do |rd|
  rd.rdoc_dir = "doc"
end

task :fixme do
  puts `grep -r FIXME * | grep -v '.svn'`
end

task :test do
  require 'tests/test_schedule'
  require 'tests/test_repy'
end

task :default => [:run] do
end

task :run do
  require 'main'
end

task :debug => [:clean] do
  $DEBUG = true
  require 'main'
end

task :distclean => [:clean] do
  File.try_unlink TTime::Data::REPY_File
end

task :cleanrun => [:clean, :run] do
end

task :recode_repy do
  repy = open(TTime::Data::REPY_File) { |f| TTime::Logic::Repy.new(f.read) }
  open('data/REPY.utf-8','w') { |f| f.write repy.unicode }
end

task :clean do
  File.try_unlink TTime::Data::YAML_File, TTime::Data::MARSHAL_File,
    'gui/ttime.gladep', 'gui/ttime.gladep.bak', 'gui/ttime.glade.bak'
end
