require 'rake'
require 'rake/testtask'

task :clean do 
   rm 'sometestfile.txt' if File.exists? 'sometestfile.txt'
end

desc 'Install the win32-file package (non-gem)'
task :install => [:clean] do
   ruby 'install.rb'
end

desc 'Install the win32-file package as a gem'
task :install_gem => [:clean] do
   ruby 'win32-file.gemspec'
   file = Dir['win32-file*.gem'].first
   sh "gem install #{file}"
end

Rake::TestTask.new("test") do |t|
   t.libs << 'test'
   t.verbose = true
   t.warning = true
   t.test_files = FileList['test/ts_all.rb']
end

Rake::TestTask.new("test_attributes") do |t|
   cp('test/sometestfile.txt', '.')
   t.verbose = true
   t.warning = true
   t.test_files = FileList['test/tc_file_attributes.rb']
end

Rake::TestTask.new("test_constants") do |t|
   t.verbose = true
   t.warning = true
   t.test_files = FileList['test/tc_file_constants.rb']
end

Rake::TestTask.new("test_encryption") do |t|
   cp('test/sometestfile.txt', '.')
   t.verbose = true
   t.warning = true
   t.test_files = FileList['test/tc_file_encryption.rb']
end

Rake::TestTask.new("test_path") do |t|
   cp('test/sometestfile.txt', '.')
   t.verbose = true
   t.warning = true
   t.test_files = FileList['test/tc_file_path.rb']
end

Rake::TestTask.new("test_security") do |t|
   cp('test/sometestfile.txt', '.')
   t.verbose = true
   t.warning = true
   t.test_files = FileList['test/tc_file_security.rb']
end

Rake::TestTask.new("test_stat") do |t|
   cp('test/sometestfile.txt', '.')
   t.verbose = true
   t.warning = true
   t.test_files = FileList['test/tc_file_stat.rb']
end