Document: ttime
Title: Debian ttime Manual
Author: <insert document author here>
Abstract: This manual describes what ttime is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ttime/ttime.sgml.gz

Format: postscript
Files: /usr/share/doc/ttime/ttime.ps.gz

Format: text
Files: /usr/share/doc/ttime/ttime.text.gz

Format: HTML
Index: /usr/share/doc/ttime/html/index.html
Files: /usr/share/doc/ttime/html/*.html

  
