#!/bin/bash

FILES=`find .|grep -v '.svn'|grep -v '^/debian'`

for x in ${FILES}; do
  if [ -d $x ]; then
    mkdir -p "$1/debian/ttime/usr/lib/ttime/$x"
  else
    cp "$x" "$1/debian/ttime/usr/lib/ttime/$x"
  fi
done

