require 'rake/rdoctask'

class File
  class << self
    def try_unlink(*files)
      files.each do |file_name|
        begin
          File.unlink file_name
        rescue Errno::ENOENT
        end
      end
    end
  end
end

Rake::RDocTask.new("doc") do |rd|
  rd.rdoc_dir = "doc"
end

desc "Find all FIXME comments"
task :fixme do
  puts `grep -r FIXME * | grep -v '.git'`
end

desc "Create mo-files for L10n"
task :makemo do
  require 'gettext/utils'
  GetText.create_mofiles(true, "po", "locale")
end

desc "Update pot/po files to match new version"
task :updatepo do
  require 'gettext/utils'
  GetText.update_pofiles("ttime",
                         Dir.glob("lib/**/*.rb") +
                         Dir.glob("share/ttime/*.glade") +
                         [ "bin/ttime" ],
                         "ttime 0.x.x")
end
